export type DietTag = "vegan" | "high-protein" | "gluten-free" | "moroccan" | "fitness" | "new" | "popular"
export type GoalTag = "perte-poids" | "prise-masse" | "energie" | "famille" | "étudiant"

export interface MenuItem {
  id: string
  name: string
  nameFr?: string
  emoji: string
  gradient: string
  description: string
  price: number
  macros: { kcal: number; protein: number; carbs: number; fat: number }
  tags: DietTag[]
  goals: GoalTag[]
  popular?: boolean
  customizable?: boolean
  size?: string
  origin?: string
}

export interface MenuCategoryData {
  slug: string
  name: string
  emoji: string
  description: string
  colorClass: string
  items: MenuItem[]
}

const BOWLS_MAROCAINS: MenuCategoryData = {
  slug: "BOWLS_MAROCAINS",
  name: "Bowls Marocains",
  emoji: "🥘",
  description: "Nos racines, revisitées",
  colorClass: "gradient-warm",
  items: [
    {
      id: "bm-couscous-tabbakh",
      name: "Couscous Tabbakh",
      emoji: "🍲",
      gradient: "gradient-plate-amber",
      description: "Couscous, légumes du jardin, poulet confit, ras el hanout, harissa côté",
      price: 72,
      macros: { kcal: 580, protein: 38, carbs: 72, fat: 14 },
      tags: ["moroccan", "high-protein"],
      goals: ["prise-masse", "energie"],
      popular: true,
      customizable: true,
      origin: "Marrakech",
    },
    {
      id: "bm-zaalouk",
      name: "Bowl Zaalouk",
      emoji: "🫙",
      gradient: "gradient-plate-orange",
      description: "Quinoa, zaalouk maison (aubergine-tomate-cumin), œuf mollet, olives noires, huile d'argan",
      price: 68,
      macros: { kcal: 420, protein: 18, carbs: 52, fat: 16 },
      tags: ["moroccan", "vegan", "gluten-free"],
      goals: ["perte-poids", "energie"],
      popular: false,
      customizable: true,
      origin: "Souss",
    },
    {
      id: "bm-kefta-oeuf",
      name: "Bowl Kefta & Œuf",
      emoji: "🥩",
      gradient: "gradient-plate-coral",
      description: "Riz brun, kefta bœuf-coriandre, œufs pochés, sauce tomate-cumin, menthe fraîche",
      price: 75,
      macros: { kcal: 610, protein: 42, carbs: 58, fat: 20 },
      tags: ["moroccan", "high-protein"],
      goals: ["prise-masse"],
      popular: true,
      customizable: true,
      origin: "Marrakech",
    },
    {
      id: "bm-chermoula",
      name: "Bowl Chermoula",
      emoji: "🐟",
      gradient: "gradient-plate-teal",
      description: "Couscous complet, filet de thon chermoula, poivrons grillés, citron confit, persil",
      price: 78,
      macros: { kcal: 490, protein: 36, carbs: 54, fat: 12 },
      tags: ["moroccan", "high-protein", "gluten-free"],
      goals: ["perte-poids", "energie"],
      popular: false,
      customizable: true,
      origin: "Essaouira",
    },
    {
      id: "bm-rfissa",
      name: "Bowl Rfissa Express",
      emoji: "🫕",
      gradient: "gradient-plate-amber",
      description: "Freekeh, poulet confit ras el hanout, lentilles, fenugrec, sauce smen",
      price: 80,
      macros: { kcal: 620, protein: 44, carbs: 68, fat: 16 },
      tags: ["moroccan", "high-protein", "new"],
      goals: ["prise-masse", "energie"],
      popular: false,
      customizable: true,
      origin: "Fès",
    },
    {
      id: "bm-bissara",
      name: "Bowl Bissara",
      emoji: "🫘",
      gradient: "gradient-plate-green",
      description: "Base orge perlé, purée de fèves bissara, huile d'olive, cumin, harissa, pain de maïs croustillant",
      price: 55,
      macros: { kcal: 380, protein: 16, carbs: 62, fat: 10 },
      tags: ["moroccan", "vegan", "gluten-free"],
      goals: ["perte-poids", "étudiant"],
      popular: false,
      customizable: false,
      origin: "Marrakech",
    },
  ],
}

const BOWLS_MONDE: MenuCategoryData = {
  slug: "BOWLS_MONDE",
  name: "Bowls du Monde",
  emoji: "🌍",
  description: "Le meilleur des cuisines du monde dans un bowl",
  colorClass: "gradient-dark",
  items: [
    {
      id: "bw-poke-saumon",
      name: "Poke Bowl Saumon",
      emoji: "🐠",
      gradient: "gradient-plate-coral",
      description: "Riz sushi, saumon mariné, edamame, avocat, concombre, sauce ponzu, sésame grillé",
      price: 85,
      macros: { kcal: 580, protein: 40, carbs: 55, fat: 18 },
      tags: ["high-protein", "gluten-free", "popular"],
      goals: ["prise-masse", "energie"],
      popular: true,
      customizable: true,
    },
    {
      id: "bw-buddha-vegan",
      name: "Buddha Bowl Vegan",
      emoji: "🧘",
      gradient: "gradient-plate-green",
      description: "Quinoa arc-en-ciel, pois chiches rôtis, betterave, avocat, tahini citronné, graines de sésame",
      price: 68,
      macros: { kcal: 540, protein: 22, carbs: 68, fat: 20 },
      tags: ["vegan", "gluten-free"],
      goals: ["perte-poids", "energie"],
      popular: true,
      customizable: true,
    },
    {
      id: "bw-thai",
      name: "Bowl Thaï",
      emoji: "🌿",
      gradient: "gradient-plate-teal",
      description: "Vermicelles de riz, tofu caramélisé, mangue, menthe fraîche, sauce cacahuète-gingembre",
      price: 70,
      macros: { kcal: 460, protein: 20, carbs: 62, fat: 14 },
      tags: ["vegan", "gluten-free"],
      goals: ["perte-poids", "étudiant"],
      popular: false,
      customizable: true,
    },
    {
      id: "bw-med-falafel",
      name: "Bowl Med Falafel",
      emoji: "🧆",
      gradient: "gradient-plate-orange",
      description: "Boulgour, falafel maison, tzatziki, tomates cerises, roquette, sumac",
      price: 72,
      macros: { kcal: 520, protein: 24, carbs: 64, fat: 18 },
      tags: ["vegan"],
      goals: ["perte-poids", "étudiant"],
      popular: false,
      customizable: true,
    },
    {
      id: "bw-power-proteines",
      name: "Power Bowl Protéines",
      emoji: "⚡",
      gradient: "gradient-plate-purple",
      description: "Riz brun, poulet grillé, œuf dur, edamame, brocoli vapeur, sauce teriyaki maison",
      price: 78,
      macros: { kcal: 620, protein: 48, carbs: 58, fat: 14 },
      tags: ["high-protein", "fitness", "gluten-free"],
      goals: ["prise-masse", "energie"],
      popular: true,
      customizable: true,
    },
  ],
}

const SALADES: MenuCategoryData = {
  slug: "SALADES",
  name: "Salades",
  emoji: "🥗",
  description: "Fraîcheur, légèreté, saveurs",
  colorClass: "gradient-plate-green",
  items: [
    {
      id: "sal-marocaine",
      name: "Salade Marocaine Classique",
      emoji: "🍅",
      gradient: "gradient-plate-coral",
      description: "Tomates, poivrons, concombre, coriandre fraîche, vinaigrette chermoula-citron",
      price: 42,
      macros: { kcal: 180, protein: 4, carbs: 22, fat: 8 },
      tags: ["moroccan", "vegan", "gluten-free"],
      goals: ["perte-poids"],
      popular: false,
      customizable: false,
      origin: "Marrakech",
    },
    {
      id: "sal-fattouche",
      name: "Salade Fattouche Marrakchie",
      emoji: "🍊",
      gradient: "gradient-plate-amber",
      description: "Mesclun, grenade, orange, feta, pain grillé à l'huile d'argan, vinaigrette citron",
      price: 52,
      macros: { kcal: 280, protein: 10, carbs: 32, fat: 12 },
      tags: ["moroccan", "gluten-free", "new"],
      goals: ["perte-poids", "energie"],
      popular: true,
      customizable: false,
      origin: "Marrakech",
    },
    {
      id: "sal-cesar",
      name: "Salade César Poulet",
      emoji: "🥬",
      gradient: "gradient-plate-green",
      description: "Romaine croquante, poulet grillé, parmesan, croûtons maison, sauce césar maison",
      price: 65,
      macros: { kcal: 480, protein: 38, carbs: 24, fat: 26 },
      tags: ["high-protein"],
      goals: ["prise-masse", "energie"],
      popular: true,
      customizable: true,
    },
    {
      id: "sal-argan-avocat",
      name: "Salade Argan & Avocat",
      emoji: "🥑",
      gradient: "gradient-plate-teal",
      description: "Épinards baby, avocat, noix, betterave, vinaigrette huile d'argan & citron",
      price: 58,
      macros: { kcal: 360, protein: 8, carbs: 20, fat: 28 },
      tags: ["vegan", "gluten-free", "moroccan"],
      goals: ["perte-poids", "energie"],
      popular: false,
      customizable: false,
      origin: "Souss",
    },
    {
      id: "sal-detox-verte",
      name: "Salade Détox Verte",
      emoji: "🌿",
      gradient: "gradient-plate-green",
      description: "Kale, concombre, pomme verte, gingembre frais, graines de courge, citron vert",
      price: 50,
      macros: { kcal: 200, protein: 6, carbs: 24, fat: 10 },
      tags: ["vegan", "gluten-free"],
      goals: ["perte-poids", "energie"],
      popular: false,
      customizable: false,
    },
  ],
}

const JUS_SMOOTHIES: MenuCategoryData = {
  slug: "JUS_SMOOTHIES",
  name: "Jus & Smoothies",
  emoji: "🍊",
  description: "Pressés minute, naturels, vrais",
  colorClass: "gradient-coral",
  items: [
    {
      id: "js-orange-marrakchi",
      name: "Jus d'Orange Pressé Marrakchi",
      emoji: "🍊",
      gradient: "gradient-plate-amber",
      description: "Oranges navel du Maroc, fraîchement pressé à la commande, sans sucre ajouté",
      price: 18,
      macros: { kcal: 110, protein: 2, carbs: 26, fat: 0 },
      tags: ["vegan", "gluten-free", "moroccan", "popular"],
      goals: ["energie", "perte-poids"],
      popular: true,
      size: "500ml",
      origin: "Marrakech",
    },
    {
      id: "js-grenade",
      name: "Jus de Grenade Naturel",
      emoji: "🍷",
      gradient: "gradient-plate-coral",
      description: "Grenades du Maroc, pur jus pressé, riche en antioxydants, sans conservateurs",
      price: 28,
      macros: { kcal: 130, protein: 2, carbs: 30, fat: 0 },
      tags: ["vegan", "gluten-free", "moroccan"],
      goals: ["energie", "perte-poids"],
      popular: false,
      size: "350ml",
      origin: "Skhirat",
    },
    {
      id: "js-avocat",
      name: "Cocktail Avocat",
      emoji: "🥑",
      gradient: "gradient-plate-green",
      description: "Avocat, lait entier, sucre de canne, eau de fleur d'oranger, pincée de cannelle",
      price: 32,
      macros: { kcal: 280, protein: 6, carbs: 22, fat: 18 },
      tags: ["moroccan", "popular", "gluten-free"],
      goals: ["energie", "prise-masse"],
      popular: true,
      size: "350ml",
      origin: "Marrakech",
    },
    {
      id: "js-menthe-citron",
      name: "Menthe-Citron Citronnade",
      emoji: "🍋",
      gradient: "gradient-plate-teal",
      description: "Menthe fraîche du Maroc, citron pressé, eau gazéifiée, peu de sucre",
      price: 20,
      macros: { kcal: 60, protein: 0, carbs: 14, fat: 0 },
      tags: ["vegan", "gluten-free", "moroccan"],
      goals: ["perte-poids", "energie"],
      popular: false,
      size: "400ml",
    },
    {
      id: "js-immunite",
      name: "Jus Immunité",
      emoji: "🫚",
      gradient: "gradient-plate-orange",
      description: "Orange, carotte, gingembre frais, curcuma, poivre noir — le shot boost du matin",
      price: 28,
      macros: { kcal: 120, protein: 2, carbs: 28, fat: 0 },
      tags: ["vegan", "gluten-free"],
      goals: ["energie", "perte-poids"],
      popular: false,
      size: "350ml",
    },
    {
      id: "js-green-detox",
      name: "Green Detox",
      emoji: "🥒",
      gradient: "gradient-plate-green",
      description: "Épinards, concombre, citron vert, pomme verte, gingembre, menthe fraîche",
      price: 32,
      macros: { kcal: 95, protein: 3, carbs: 20, fat: 1 },
      tags: ["vegan", "gluten-free"],
      goals: ["perte-poids"],
      popular: false,
      size: "400ml",
    },
    {
      id: "js-smoothie-post-training",
      name: "Smoothie Protéiné Post-Training",
      emoji: "💪",
      gradient: "gradient-plate-purple",
      description: "Banane, lait d'amande, whey vanille, graines de chia, miel du Maroc",
      price: 42,
      macros: { kcal: 340, protein: 28, carbs: 42, fat: 6 },
      tags: ["high-protein", "fitness", "gluten-free"],
      goals: ["prise-masse", "energie"],
      popular: true,
      size: "500ml",
    },
    {
      id: "js-smoothie-atlas",
      name: "Smoothie Atlas",
      emoji: "🏔️",
      gradient: "gradient-plate-amber",
      description: "Dattes Medjool, lait entier, amandes, cannelle de Ceylan, eau de rose",
      price: 35,
      macros: { kcal: 290, protein: 10, carbs: 38, fat: 10 },
      tags: ["moroccan", "gluten-free"],
      goals: ["energie", "prise-masse"],
      popular: false,
      size: "400ml",
      origin: "Atlas",
    },
  ],
}

const BOISSONS: MenuCategoryData = {
  slug: "BOISSONS",
  name: "Boissons",
  emoji: "💧",
  description: "Eaux et thés du Maroc",
  colorClass: "gradient-dark",
  items: [
    {
      id: "bo-sidi-ali-500",
      name: "Eau Sidi Ali 500ml",
      emoji: "💧",
      gradient: "gradient-plate-teal",
      description: "Eau minérale naturelle du Maroc, fraîche, servie froide",
      price: 8,
      macros: { kcal: 0, protein: 0, carbs: 0, fat: 0 },
      tags: ["vegan", "gluten-free"],
      goals: ["perte-poids", "energie"],
      popular: false,
      size: "500ml",
    },
    {
      id: "bo-sidi-ali-1l",
      name: "Eau Sidi Ali 1L",
      emoji: "🫙",
      gradient: "gradient-plate-teal",
      description: "Grande bouteille famille, eau minérale naturelle du Maroc",
      price: 12,
      macros: { kcal: 0, protein: 0, carbs: 0, fat: 0 },
      tags: ["vegan", "gluten-free"],
      goals: ["famille"],
      popular: false,
      size: "1L",
    },
    {
      id: "bo-ain-saiss",
      name: "Eau Pétillante Ain Saiss",
      emoji: "🫧",
      gradient: "gradient-plate-teal",
      description: "Eau gazéifiée fraîche, bulles naturelles, rafraîchissante",
      price: 12,
      macros: { kcal: 0, protein: 0, carbs: 0, fat: 0 },
      tags: ["vegan", "gluten-free"],
      goals: ["perte-poids"],
      popular: false,
      size: "330ml",
    },
    {
      id: "bo-eau-infusee",
      name: "Eau Infusée Maison",
      emoji: "🌿",
      gradient: "gradient-plate-green",
      description: "Eau filtrée, menthe fraîche, citron tranché, rondelles de concombre",
      price: 15,
      macros: { kcal: 10, protein: 0, carbs: 2, fat: 0 },
      tags: ["vegan", "gluten-free"],
      goals: ["perte-poids", "energie"],
      popular: false,
      size: "500ml",
    },
    {
      id: "bo-the-menthe",
      name: "Thé Vert à la Menthe",
      emoji: "🍵",
      gradient: "gradient-plate-green",
      description: "Thé gunpowder, menthe fraîche du jardin, sucre traditionnel ou stevia au choix",
      price: 15,
      macros: { kcal: 30, protein: 0, carbs: 7, fat: 0 },
      tags: ["vegan", "gluten-free", "moroccan"],
      goals: ["perte-poids", "energie"],
      popular: true,
      size: "300ml",
      origin: "Marrakech",
    },
    {
      id: "bo-lben",
      name: "Lben Frais",
      emoji: "🥛",
      gradient: "gradient-plate-teal",
      description: "Lait fermenté traditionnel marocain, frais et naturel, riche en probiotiques",
      price: 12,
      macros: { kcal: 90, protein: 6, carbs: 8, fat: 4 },
      tags: ["moroccan", "gluten-free"],
      goals: ["prise-masse", "energie"],
      popular: false,
      size: "250ml",
      origin: "Marrakech",
    },
  ],
}

const SNACKS: MenuCategoryData = {
  slug: "SNACKS",
  name: "Snacks & Douceurs",
  emoji: "🍫",
  description: "L'énergie entre les repas",
  colorClass: "gradient-warm",
  items: [
    {
      id: "sn-dattes-amandes",
      name: "Dattes Medjool & Amandes",
      emoji: "🌴",
      gradient: "gradient-plate-amber",
      description: "5 dattes Medjool premium du Maroc + amandes grillées nature, riche en magnésium",
      price: 28,
      macros: { kcal: 220, protein: 6, carbs: 36, fat: 10 },
      tags: ["vegan", "gluten-free", "moroccan"],
      goals: ["energie", "étudiant"],
      popular: true,
      origin: "Errachidia",
    },
    {
      id: "sn-chocolat-noir",
      name: "Chocolat Noir 85%",
      emoji: "🍫",
      gradient: "gradient-plate-purple",
      description: "Barre de chocolat noir artisanal 70g, riche en antioxydants, 85% cacao",
      price: 25,
      macros: { kcal: 380, protein: 8, carbs: 14, fat: 32 },
      tags: ["vegan", "gluten-free"],
      goals: ["energie", "étudiant"],
      popular: false,
    },
    {
      id: "sn-energy-ball",
      name: "Energy Ball Marocaine",
      emoji: "⚡",
      gradient: "gradient-plate-orange",
      description: "Dattes, sésame, amandes, cannelle, noix de coco râpée — lot de 3 boules",
      price: 25,
      macros: { kcal: 240, protein: 6, carbs: 30, fat: 12 },
      tags: ["vegan", "gluten-free", "moroccan", "fitness"],
      goals: ["energie", "prise-masse"],
      popular: true,
    },
    {
      id: "sn-barre-cereales",
      name: "Barre de Céréales Maison",
      emoji: "🌾",
      gradient: "gradient-plate-amber",
      description: "Avoine, miel de l'arganier, graines de courge, cranberry, sans additifs",
      price: 20,
      macros: { kcal: 200, protein: 6, carbs: 32, fat: 6 },
      tags: ["vegan"],
      goals: ["energie", "étudiant"],
      popular: false,
    },
    {
      id: "sn-houmous-pita",
      name: "Houmous & Pain Pita",
      emoji: "🫓",
      gradient: "gradient-plate-teal",
      description: "Houmous maison 80g, paprika fumé, huile d'olive + pain pita complet chaud ×2",
      price: 32,
      macros: { kcal: 320, protein: 12, carbs: 42, fat: 10 },
      tags: ["vegan"],
      goals: ["étudiant", "energie"],
      popular: false,
    },
    {
      id: "sn-noix-cajou",
      name: "Noix de Cajou Grillées",
      emoji: "🥜",
      gradient: "gradient-plate-orange",
      description: "100g de noix de cajou légèrement salées, source de magnésium et de bonnes graisses",
      price: 22,
      macros: { kcal: 560, protein: 16, carbs: 28, fat: 44 },
      tags: ["vegan", "gluten-free"],
      goals: ["prise-masse", "étudiant"],
      popular: false,
    },
  ],
}

const FITNESS_SUPPLEMENTS: MenuCategoryData = {
  slug: "FITNESS_SUPPLEMENTS",
  name: "Compléments Fitness",
  emoji: "💊",
  description: "Pour booster vos performances",
  colorClass: "gradient-dark",
  items: [
    {
      id: "fs-whey-vanille",
      name: "Whey Protéine Vanille",
      emoji: "🍦",
      gradient: "gradient-plate-teal",
      description: "1 dose 30g + lait ou eau, mélangé minute devant vous — 21g de protéines par dose",
      price: 35,
      macros: { kcal: 130, protein: 21, carbs: 6, fat: 2 },
      tags: ["high-protein", "fitness", "gluten-free"],
      goals: ["prise-masse"],
      popular: true,
    },
    {
      id: "fs-whey-choco",
      name: "Whey Protéine Chocolat Noir",
      emoji: "🍫",
      gradient: "gradient-plate-purple",
      description: "1 dose 30g, cacao Valrhona de qualité, 21g de protéines par dose",
      price: 35,
      macros: { kcal: 130, protein: 21, carbs: 6, fat: 2 },
      tags: ["high-protein", "fitness", "gluten-free"],
      goals: ["prise-masse"],
      popular: false,
    },
    {
      id: "fs-bcaa",
      name: "BCAA Pastèque",
      emoji: "🍉",
      gradient: "gradient-plate-coral",
      description: "Sachet 10g, acides aminés ramifiés, optimise la récupération musculaire",
      price: 20,
      macros: { kcal: 25, protein: 6, carbs: 1, fat: 0 },
      tags: ["fitness", "gluten-free"],
      goals: ["prise-masse", "energie"],
      popular: false,
    },
    {
      id: "fs-creatine",
      name: "Créatine Monohydrate",
      emoji: "⚗️",
      gradient: "gradient-plate-teal",
      description: "Sachet 5g de créatine pure, améliore la force et la performance, à ajouter à votre boisson",
      price: 15,
      macros: { kcal: 0, protein: 0, carbs: 0, fat: 0 },
      tags: ["fitness", "gluten-free"],
      goals: ["prise-masse"],
      popular: false,
    },
    {
      id: "fs-barre-atlas",
      name: "Barre Protéinée Atlas",
      emoji: "🏔️",
      gradient: "gradient-plate-amber",
      description: "20g de protéines, 210 kcal, saveur dattes-amandes marocaine — sans sirop de glucose",
      price: 32,
      macros: { kcal: 210, protein: 20, carbs: 18, fat: 6 },
      tags: ["high-protein", "fitness", "moroccan", "new"],
      goals: ["prise-masse", "energie"],
      popular: true,
    },
    {
      id: "fs-shaker",
      name: "Shaker Healthy Bowl 700ml",
      emoji: "🥤",
      gradient: "gradient-plate-green",
      description: "Shaker gradué avec logo Healthy Bowl, anti-fuite, livré rempli d'eau fraîche",
      price: 45,
      macros: { kcal: 0, protein: 0, carbs: 0, fat: 0 },
      tags: ["fitness"],
      goals: ["prise-masse"],
      popular: false,
    },
  ],
}

const BOXES_FAMILLE: MenuCategoryData = {
  slug: "BOXES_FAMILLE",
  name: "Boxes & Packs",
  emoji: "📦",
  description: "Partagez, économisez, régalez-vous",
  colorClass: "gradient-green",
  items: [
    {
      id: "bf-couple",
      name: "Box Couple",
      emoji: "👫",
      gradient: "gradient-plate-green",
      description: "2 bowls au choix + 2 jus frais pressés, livraison prioritaire",
      price: 160,
      macros: { kcal: 1100, protein: 70, carbs: 120, fat: 32 },
      tags: ["popular"],
      goals: ["famille"],
      popular: true,
      customizable: true,
    },
    {
      id: "bf-famille-4",
      name: "Box Famille 4 Personnes",
      emoji: "👨‍👩‍👧‍👦",
      gradient: "gradient-plate-amber",
      description: "4 bowls + 4 eaux Sidi Ali 500ml + 4 snacks, économisez 60 MAD sur le prix séparé",
      price: 320,
      macros: { kcal: 2200, protein: 140, carbs: 240, fat: 64 },
      tags: ["popular"],
      goals: ["famille"],
      popular: true,
      customizable: true,
    },
    {
      id: "bf-post-training",
      name: "Box Post-Training",
      emoji: "🏋️",
      gradient: "gradient-plate-purple",
      description: "1 bowl protéiné + 1 smoothie protéiné + 1 dose whey, la récupération parfaite",
      price: 125,
      macros: { kcal: 900, protein: 80, carbs: 90, fat: 20 },
      tags: ["fitness", "high-protein"],
      goals: ["prise-masse", "energie"],
      popular: false,
      customizable: false,
    },
    {
      id: "bf-etudiant-semaine",
      name: "Box Étudiant Semaine",
      emoji: "🎓",
      gradient: "gradient-plate-teal",
      description: "5 bowls au choix (1 par jour, lun-ven), prépayé, économisez 40 MAD sur la semaine",
      price: 310,
      macros: { kcal: 2800, protein: 180, carbs: 260, fat: 60 },
      tags: ["fitness"],
      goals: ["étudiant", "perte-poids"],
      popular: false,
      customizable: true,
    },
    {
      id: "bf-pique-nique",
      name: "Box Pique-nique Marocain",
      emoji: "🧺",
      gradient: "gradient-plate-orange",
      description: "2 salades + 2 jus frais + pain pita + dattes & amandes — parfait pour une sortie",
      price: 140,
      macros: { kcal: 800, protein: 30, carbs: 110, fat: 28 },
      tags: ["moroccan"],
      goals: ["famille", "energie"],
      popular: false,
      customizable: false,
    },
  ],
}

export const MENU_CATEGORIES: MenuCategoryData[] = [
  BOWLS_MAROCAINS,
  BOWLS_MONDE,
  SALADES,
  JUS_SMOOTHIES,
  BOISSONS,
  SNACKS,
  FITNESS_SUPPLEMENTS,
  BOXES_FAMILLE,
]

export interface FitnessSpot {
  id: string
  name: string
  area: string
  emoji: string
  deliveryTime: string
  schedule: string
  distance: string
  type: "gym" | "stadium" | "campus" | "pool"
  color: string
}

export const FITNESS_SPOTS: FitnessSpot[] = [
  { id: "al-boustane", name: "Al Boustane Fitness", area: "Guéliz", emoji: "🏋️", deliveryTime: "12 min", schedule: "6h30–23h", distance: "1.2 km", type: "gym", color: "orange" },
  { id: "o-club", name: "O'Club Marrakech", area: "Hivernage", emoji: "💪", deliveryTime: "18 min", schedule: "7h–22h", distance: "2.1 km", type: "gym", color: "blue" },
  { id: "stade-elharti", name: "Stade El Harti", area: "Médina", emoji: "🏟️", deliveryTime: "10 min", schedule: "6h–21h", distance: "0.8 km", type: "stadium", color: "green" },
  { id: "cadi-ayyad", name: "Campus Cadi Ayyad", area: "Route Casablanca", emoji: "🎓", deliveryTime: "20 min", schedule: "8h–20h", distance: "3.2 km", type: "campus", color: "purple" },
  { id: "palmeraie-golf", name: "Palmeraie Sports Club", area: "Palmeraie", emoji: "🌴", deliveryTime: "25 min", schedule: "7h–22h", distance: "5.5 km", type: "gym", color: "emerald" },
  { id: "complexe-olympic", name: "Complexe Olympique", area: "Sidi Youssef Ben Ali", emoji: "🏊", deliveryTime: "15 min", schedule: "7h–21h", distance: "1.8 km", type: "pool", color: "cyan" },
]
